version: 1.0.{build}

before_build:
  - nuget restore
configuration: Debug

platform: Any CPU
image: Visual Studio 2012

build:
  project: Route4Me Route Optimization Examples.sln 
  verbosity: minimal
  
after_test: 
    - packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe" -targetargs:"/noresults /noisolation /testcontainer:"".\Route4meSDKLibraryUnitTests\bin\Debug\Route4meSDKLibraryUnitTests.dll" 
    