# Version format
version: 1.0{build}

# Build worker image
image: Visual Studio 2019

branches:
  only:
  - master

# Build platform
platform: Any CPU

# Build Configuration
configuration: 
  - Appveyor

# Execute script before build
before_build:
  # Display .net version
  - cmd: dotnet --version
#  - nuget restore "%solution_name%"
  - cmd: dotnet restore "route4me-vbnet-sdk/Route4MeSDKLibrary/Route4MeSDKLibrary.csproj"
#  - cmd: dotnet restore "route4me-vbnet-sdk/Route4meSDKLibraryUnitTests/Route4meSDKUnitTest.csproj"

# MSBuild settings
build_script:
  - dotnet build "route4me-vbnet-sdk/Route4MeSDKLibrary/Route4MeSDKLibrary.vbproj"

build:
  verbosity: minimal
  
test_script:
  # restore packages for mstest unit tests and run tests
  # - cmd: dotnet restore ./Route4meSDKLibraryUnitTests/Route4meSDKUnitTest.csproj --verbosity m
  # - cmd: cd Route4meSDKLibraryUnitTests
  # - cmd: dotnet mstest
  
  # - cmd: dotnet restore ./Route4MeSdkV5UnitTest/Route4MeSdkV5UnitTest.csproj --verbosity m
  # - cmd: cd Route4MeSdkV5UnitTest
  # - cmd: dotnet xunit

only_commits:
  files:
  - route4me-vbnet-sdk\Route4MeSDKLibrary\

# Omitted the tests, as they are not relevant for the question